const tableData = [
   {
      gtsOrderId: "713377",
      voucher: "9DGCQEQD",
      transaction: "booked",
      transactionDate: "4/3/24",
      checkIn: "4/4/24",
      checkOut: "4/6/24",
      Room: "1",
      Pax: "1",
      Currency: "EUR",
      amounPayable: "318.15 €",
      hotelName: "Radisson Collection  Hotel, Vadistanbul",
      City: "Istanbul",
      Country: "Türkiye",
   },
   {
      gtsOrderId: "714262",
      voucher: "LXPMBJKR",
      transaction: "booked",
      transactionDate: "4/4/24",
      checkIn: "4/22/24",
      checkOut: "4/24/24",
      Room: "1",
      Pax: "2",
      Currency: "EUR",
      amounPayable: "140.59 €",
      hotelName: "Hotel The Pera Hill",
      City: "Istanbul",
      Country: "Türkiye",
   },
   {
      gtsOrderId: "720802",
      voucher: "BPBQUJHE",
      transaction: "booked",
      transactionDate: "4/9/24",
      checkIn: "4/10/24",
      checkOut: "4/13/24",
      Room: "1",
      Pax: "2",
      Currency: "EUR",
      amounPayable: "432.60 €",
      hotelName: "DoubleTree by Hilton  Hotel Istanbul - Sirkeci",
      City: "Istanbul",
      Country: "Türkiye",
   },
   {
      gtsOrderId: "716206",
      voucher: "9AXTLUDV",
      transaction: "booked",
      transactionDate: "4/5/24",
      checkIn: "4/25/24",
      checkOut: "4/27/24",
      Room: "1",
      Pax: "2",
      Currency: "EUR",
      amounPayable: "143.38 €",
      hotelName: "Hotel The Pera Hill",
      City: "Istanbul",
      Country: "Türkiye",
   },
   {
      gtsOrderId: "719757",
      voucher: "OSWRUPHX",
      transaction: "booked",
      transactionDate: "4/8/24",
      checkIn: "4/19/24",
      checkOut: "4/22/24",
      Room: "1",
      Pax: "2",
      Currency: "EUR",
      amounPayable: "305.91 €",
      hotelName: "Skalion Hotel & SPA",
      City: "Istanbul",
      Country: "Türkiye",
   },
   {
      gtsOrderId: "719716",
      voucher: "AQKRDWJA",
      transaction: "booked",
      transactionDate: "4/8/24",
      checkIn: "4/28/24",
      checkOut: "4/30/24",
      Room: "1",
      Pax: "3",
      Currency: "EUR",
      amounPayable: "175.10 €",
      hotelName: "Beyazit Palace Hotel",
      City: "Istanbul",
      Country: "Türkiye",
   },
   {
      gtsOrderId: "757606",
      voucher: "PWFGM3GH",
      transaction: "booked",
      transactionDate: "4/29/24",
      checkIn: "4/29/24",
      checkOut: "5/4/24",
      Room: "1",
      Pax: "2",
      Currency: "EUR",
      amounPayable: "618.00 €",
      hotelName: "Hotel Yasmak Sultan",
      City: "Istanbul",
      Country: "Türkiye",
   },
   {
      gtsOrderId: "754186",
      voucher: "YFX6HHV5",
      transaction: "booked",
      transactionDate: "4/27/24",
      checkIn: "4/29/24",
      checkOut: "5/4/24",
      Room: "2",
      Pax: "4",
      Currency: "EUR",
      amounPayable: "968.20 €",
      hotelName: "Ramada by Wyndham Is tanbul Taksim",
      City: "Istanbul",
      Country: "Türkiye",
   },
   {
      gtsOrderId: "729139",
      voucher: "UGYFP8HO",
      transaction: "booked",
      transactionDate: "4/14/24",
      checkIn: "4/18/24",
      checkOut: "4/21/24",
      Room: "1",
      Pax: "2",
      Currency: "EUR",
      amounPayable: "262.65 €",
      hotelName: "Ramada by Wyndham Is tanbul Taksim",
      City: "Istanbul",
      Country: "Türkiye",
   },
   {
      gtsOrderId: "745447",
      voucher: "AZPUIYCM",
      transaction: "booked",
      transactionDate: "4/23/24",
      checkIn: "4/24/24",
      checkOut: "4/26/24",
      Room: "1",
      Pax: "1",
      Currency: "EUR",
      amounPayable: "118.66 €",
      hotelName: "Hotel The Pera Hill",
      City: "Istanbul",
      Country: "Türkiye",
   },
   {
      gtsOrderId: "726221",
      voucher: "KVQETB3Y",
      transaction: "booked",
      transactionDate: "4/12/24",
      checkIn: "4/12/24",
      checkOut: "4/13/24",
      Room: "1",
      Pax: "2",
      Currency: "EUR",
      amounPayable: "67.09 €",
      hotelName: "Grand Makel Hotel To pkapi",
      City: "Istanbul",
      Country: "Türkiye",
   },
   {
      gtsOrderId: "737136",
      voucher: "MU9YN8L2",
      transaction: "booked",
      transactionDate: "4/18/24",
      checkIn: "4/19/24",
      checkOut: "4/20/24",
      Room: "1",
      Pax: "2",
      Currency: "EUR",
      amounPayable: "88.99 €",
      hotelName: "Doubletree by Hilton  İstanbul Umraniye",
      City: "Istanbul",
      Country: "Türkiye",
   },
   //fason
];

export default tableData;
